source 'http://rubygems.org'

gem 'rails', '3.2.8'
gem 'pg', '0.11'
gem 'kissfft'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'will_paginate', '~> 3.0'
gem 'dynamic_form'
